### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by amerkich** [odigoteam/odigo-environment-linker#57]
### Description
[Short description of your issue]

### Steps to reproduce
[what you've done to get this issue]

### Technical infos
Extension version : 4.15.2
Git hash : gabbaf25

### Datas
```
TypeError: Cannot read properties of undefined (reading 'length')
    at V$ (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:379065)
    at Hy (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:58419)
    at Bc (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57210)
    at sk (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57635)
    at Bc (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57660)
    at sk (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57635)
    at Bc (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57660)
    at sk (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57635)
    at Bc (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57660)
    at sk (chrome-extension://hmoildjcecmecojmmefoeclflnojbflj/main.c608db98ef2407a9.js:1:57635)
```

**Comment by levyndot** [comment]
Can you please complete the [Description] and [Steps to reproduce]. Without what, I can't do anything for your issue... 😅
